force-app/main/default/objects/Inhabitant__c/Inhabitant__c.object-meta.xml
<CustomObject>
    <label>Inhabitant</label>
    <nameField>
        <displayFormat>Inhab-{00000000}</displayFormat>
        <label>Inhabitant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inhabitants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inhabitant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Inhabitants</relationshipLabel>
    <relationshipName>Inhabitants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <inlineHelpText>Please enter height in inches</inlineHelpText>
    <label>Height</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Inhabitant__c.field-meta.xml
<CustomField>
    <fullName>Inhabitant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inhabitant</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the customer insured their mail?</description>
    <label>Insurance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Insured_Value__c.field-meta.xml
<CustomField>
    <fullName>Insured_Value__c</fullName>
    <inlineHelpText>Please enter the amount insured for to the nearest whole dollar.</inlineHelpText>
    <label>Insured Value</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <inlineHelpText>Please enter width in inches</inlineHelpText>
    <label>Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Thickness__c.field-meta.xml
<CustomField>
    <fullName>Thickness__c</fullName>
    <label>Thickness</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <inlineHelpText>Please enter weight in ounces</inlineHelpText>
    <label>Weight</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>At Facility</fullName>
    </customValue>
    <customValue>
        <fullName>En Route</fullName>
    </customValue>
    <customValue>
        <fullName>Delivered</fullName>
    </customValue>
    <customValue>
        <fullName>Missing</fullName>
    </customValue>
    <masterLabel>Delivery Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HomePageController.cls
public with sharing class HomePageController {


    public HomePageController(ApexPages.StandardController stdController) {}

    public List<Mail__c> AllUserMail{
        /*User hold1 = [SELECT Id, Alias FROM User WHERE Username='externaluser1614450360435@company.com'];
        User hold = [SELECT Id, Name, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
        */
        get {
            if(AllUserMail==null){
                AllUserMail = new List<Mail__c>();
        
                User currentUser = [SELECT Id, ContactId FROM User WHERE Id=:UserInfo.getUserId()];

                for(Mail__c mail : [SELECT Id, Name, Delivery_Status__c, Height__c, Length__c, Thickness__c, Weight__c, Insurance__c, Insured_Value__c FROM Mail__c WHERE Inhabitant__r.Contact__c = :currentUser.ContactId]){
                AllUserMail.add(mail);
                }
            }
        return AllUserMail;
        }
        set;
    }
    
    
}