force-app/main/default/objects/Inhabitant__c/Inhabitant__c.object-meta.xml
<CustomObject>
    <label>Inhabitant</label>
    <nameField>
        <displayFormat>Inhab-{00000000}</displayFormat>
        <label>Inhabitant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inhabitants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inhabitant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Inhabitants</relationshipLabel>
    <relationshipName>Inhabitants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mail__c/fields/Inhabitant__c.field-meta.xml
<CustomField>
    <fullName>Inhabitant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inhabitant</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Tobedeleted.cls
public class Tobedeleted {
    
    public static void tbd(){
        User currentUser=[SELECT Id, Alias, ContactId FROM User WHERE Name='John Severo'];
        List<Mail__c> mails = new List<Mail__c>();
        for(Mail__c mail : [SELECT Id, Name FROM Mail__c WHERE Inhabitant__r.Contact__c = :currentUser.ContactId]){
            mails.add(mail);
        }
        
        System.debug(currentUser);
    }

}