force-app/main/default/objects/Inhabitant__c/Inhabitant__c.object-meta.xml
<CustomObject>
    <label>Inhabitant</label>
    <nameField>
        <displayFormat>Inhab-{00000000}</displayFormat>
        <label>Inhabitant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inhabitants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inhabitant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Inhabitants</relationshipLabel>
    <relationshipName>Inhabitants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <inlineHelpText>Please enter height in inches</inlineHelpText>
    <label>Height</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Inhabitant__c.field-meta.xml
<CustomField>
    <fullName>Inhabitant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inhabitant</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the customer insured their mail?</description>
    <label>Insurance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Insured_Value__c.field-meta.xml
<CustomField>
    <fullName>Insured_Value__c</fullName>
    <inlineHelpText>Please enter the amount insured for to the nearest whole dollar.</inlineHelpText>
    <label>Insured Value</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <inlineHelpText>Please enter width in inches</inlineHelpText>
    <label>Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Thickness__c.field-meta.xml
<CustomField>
    <fullName>Thickness__c</fullName>
    <label>Thickness</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <inlineHelpText>Please enter weight in ounces</inlineHelpText>
    <label>Weight</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>At Facility</fullName>
    </customValue>
    <customValue>
        <fullName>En Route</fullName>
    </customValue>
    <customValue>
        <fullName>Delivered</fullName>
    </customValue>
    <customValue>
        <fullName>Missing</fullName>
    </customValue>
    <masterLabel>Delivery Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HomePageListDeliveredMailPage.cls
public inherited sharing class HomePageListDeliveredMailPage {
    public Integer recordCount{get;set;}
    public static Integer pageSize = 6;


    public ApexPages.StandardSetController setCon{
        get {

            if(setCon==null){
                //User currentUser = [SELECT Id, ContactId FROM User WHERE Id=:UserInfo.getUserId()]; 
                //Above is final code; below is for testing purposes
                User currentUser = [SELECT Id, ContactId FROM User WHERE Id='0054x000004KA2MAAW'];
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator([SELECT Id, Name, Delivery_Status__c, Height__c, Length__c, Thickness__c, Weight__c, Insurance__c, Insured_Value__c FROM Mail__c WHERE Inhabitant__r.Contact__c = :currentUser.ContactId AND Delivery_Status__c = 'Delivered' ORDER BY Name]));
                setCon.setPageSize(pageSize);
                recordCount = setCon.getResultSize();
            }
        return setCon;
        }
        set;

    }

    public List<Mail__c> getDeliveredMail(){
        List<Mail__c> mailList = new List<Mail__c>();
        List<Mail__c> records = setCon.getRecords();
        for(Mail__c mail : records){
                mailList.add(mail);
        }
        return mailList;
    }
    public Boolean hasNext{
        get{
            return setCon.getHasNext();
        }
        private set;
    }
    public Boolean hasPrevious{
        get{
            return setCon.getHasPrevious();
        }
        private set;
    }
    public Integer pageNumber {
        get{
            return setCon.getPageNumber();
        }
        private set;
    }
    public void first(){
        setCon.first();
    }
    public void last(){
        setCon.last();
    }
    public void previous(){
        setCon.previous();
    }
    public void next(){
        setCon.next();
    }

}