force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mail__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the customer insured their mail?</description>
    <label>Insurance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Insured_Value__c.field-meta.xml
<CustomField>
    <fullName>Insured_Value__c</fullName>
    <inlineHelpText>Please enter the amount insured for to the nearest whole dollar.</inlineHelpText>
    <label>Insured Value</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <formula>Inhabitant__r.Contact__r.FirstName + &quot; &quot; +  Inhabitant__r.Contact__r.LastName + BR() + Inhabitant__r.Address__r.Mailing_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Recipient</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Submit_For_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Submit_For_Insurance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check to start the insurance claim approval process</description>
    <label>Submit For Insurance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>At Facility</fullName>
    </customValue>
    <customValue>
        <fullName>En Route</fullName>
    </customValue>
    <customValue>
        <fullName>Delivered</fullName>
    </customValue>
    <customValue>
        <fullName>Missing</fullName>
    </customValue>
    <masterLabel>Delivery Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TrackingController.cls
public with sharing class TrackingController {
     public Mail__c mailne {get; set;}
     public Integer tra {get; set;}
     public Boolean isvis{get; set;}
     public Boolean shoerror{get; set;} 
     public Boolean inshow{get; set;}
     public Boolean payout{get; set;}
   //  public String recep{get; set;}

    public TrackingController() {
        isvis=false;
        payout=false;
        inshow=false;
        shoerror=false;
        mailne =new Mail__c();
    
    
    }
    public Pagereference search(){
        String converttra=String.valueOf(tra);
        List<Mail__c>  tempmail=[SELECT Delivery_Status__c,Recipient__C,Name,Insurance__C,Insured_Value__c,Submit_For_Insurance__c,Approval_Status__c FROM Mail__c ];
       for(Mail__c c:tempmail){
         Integer n =Integer.valueOf(c.name);
           if(n==tra){
            isvis=true;
            mailne=c;
          //  recep=mailne.Recipient__C.replaceAll('<br>', ', ');
            shoerror=false;
            if(c.Insurance__c==true){
                inshow=true;
                if(c.Submit_For_Insurance__c==true){
                    payout=true;
                }
            }
           break;
        }else {
            isvis=false;
            isvis=false;
            shoerror=true;
            payout=false;
        }
    }
        return null;
    }
}